def to_camel_case_strip_spaces(the_string: str) -> str: ...
def to_camel_case_with_underscores(the_string: str) -> str: ...
def to_pascal_case_strip_spaces(the_string: str) -> str: ...
def to_pascal_case_with_underscores(the_string: str) -> str: ...
def to_upper_case_with_underscores(the_string: str) -> str: ...