from asyncio import Protocol
from typing import Any


class _GetItem(Protocol):
    def __getitem__(self, key): ...


def dict_util_swap_key_values(the_dict: dict) -> dict: ...

def dict_util_remap(the_dict: dict, key_map: dict | _GetItem) -> dict: ...

def dict_util_get_first_non_null(the_dict: dict, *fields: Any, default: Any = None) -> Any: ...

def dict_util_try_del(the_dict: dict, key: Any) -> None: ...